import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class CinemaConnection {
    private static void createDB(Connection c) throws SQLException {
        PreparedStatement tableHalls = c.prepareStatement(
                "CREATE TABLE HALLS(" +
                        "NUM INT NOT NULL," +
                        "NROWS INT NOT NULL)"
        );
        tableHalls.execute();
        PreparedStatement tableSeances = c.prepareStatement(
                "CREATE TABLE SEANCES(" +
                        "ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100)" +
                        "PRIMARY KEY," +
                        "STIME VARCHAR(5) NOT NULL," +
                        "FILM VARCHAR(100) NOT NULL," +
                        "HALL INT NOT NULL," +
                        "AGE INT NOT NULL," +
                        "PRICE INT NOT NULL," +
                        "FOREIGN KEY (HALL)" +
                        "   REFERENCES HALLS(NUM))"
        );
        tableSeances.execute();
        PreparedStatement tableReservations = c.prepareStatement(
                "CREATE TABLE RESERVATIONS(" +
                        "USERID INT NOT NULL," +
                        "ROW INT NOT NULL," +
                        "SEAT INT NOT NULL," +
                        "FOREIGN KEY (SEANCE)" +
                        "   REFERENCES SEANCES(ID))" // todo: add DATEFROM
        );
        tableReservations.execute();
        PreparedStatement tableRows = c.prepareStatement(
                "CREATE TABLE ROWS(" +
                        "HALL INT NOT NULL," +
                        "ROW INT NOT NULL," +
                        "SEATS INT NOT NULL)"
        );
        tableRows.execute();
    }



    public Connection getConnection() throws SQLException {
        Connection c;
        try {
            return DriverManager.getConnection("jdbc:derby:CinemaDB;create=true");
        } catch (SQLException e) {
             c = DriverManager.getConnection("jdbc:derby:CinemaDB;create=true");
        }
        createDB(c);
        return c;
    }

}
