import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

/**
 * Created by IIS on 10.03.2016.
 */
public class DConnection{
    private static void createDB(Connection c) throws SQLException {
        PreparedStatement HALLS = c.prepareStatement("CREATE TABLE HALLS (" +
                "NUM  INT NOT NULL " +
                "PRIMARY KEY, " +
                "NROWS INT NOT NULL)");
        HALLS.execute();
        PreparedStatement SEANCES = c.prepareStatement("CREATE TABLE SEANCES (" +
                "ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY, " +
                "STIME TIMESTAMP NOT NULL,FILM VARCHAR(15), " +
                "HALL INT NOT NULL," +
                "AGE  INT NOT NULL, " +
                "PRICE INT NOT NULL," +
                "FOREIGN KEY (HALL) REFERENCES HALLS (NUM)" +
                ")");
        SEANCES.execute();
        PreparedStatement RESERVATIONS = c.prepareStatement("CREATE TABLE RESERVATIONS (" +
                "USERID INT NOT NULL, " +
                "ROW INT NOT NULL, " +
                "SEAT INT NOT NULL, " +
                "SEANCE INT NOT NULL," +
                "FOREIGN KEY (SEANCE) REFERENCES SEANCES (ID))");
        RESERVATIONS.execute();

    }

    public static Connection getConnection() throws SQLException {
        try{
            return DriverManager.getConnection("jdbc:derby:CinemaDB;create=true");
        }catch(SQLException e){
            Connection c = DriverManager.getConnection("jdbc:derby:CinemaDB;create=true");
            createDB(c);
            return c;
        }
    }}
